### ISSUE TITLE
Multiple versions of dotnet sdk

### ISSUE THREAD

**Issue by geowarin-sg** [ScoopInstaller/Versions#407] opened 2022-02-02 11:28 UTC
## Bug Report

dotnet-sdk (main)
dotnet5-sdk (versions)

### Current Behaviour

I would like `dotnet --list-sdks` to have both sdks listed.
Currently, only one is installed at a time and I need `scoop reset dotnet-sdk` or `scoop reset dotnet5-sdk` to switch between them.

### Expected Behaviour

`dotnet --list-sdks` should have both versions listed.

### Additional context/output

Dotnet sdks are meant to be used together in different versions. Users can use a global.json file in their project to use the correct sdk per project.

### Possible Solution

All the sdk are symliked in a common directory (DOTNET_ROOT).
Only the most recent/main version is in path.

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.1.3

**Comment by rashil2000** [comment] 2022-02-02 13:04
Duplicate of https://github.com/ScoopInstaller/Main/issues/874

**Closed by rashil2000** 2022-02-02 13:04 UTC
Labels: bug
